apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
type: Opaque
data:
  # Base64 encoded value of the Groq API key
  groq-api-key: Z3NrXzQ1d3VmRXhUM1c0NTN4SlZDZUJkV0dkeWIzcVlVYlJRWXFtQzdYNVljcnlFRkJ1RUpscG4= 