apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
type: Opaque
data:
  # Base64 encoded values: echo -n "postgres" | base64
  username: cG9zdGdyZXM=
  # Base64 encoded values: echo -n "152300" | base64
  password: MTUyMzAw 