apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=  # postgres in base64
  POSTGRES_PASSWORD: MTUyMzAw    # 152300 in base64
  POSTGRES_DB: Z2VzdGlvbl9waGFybWFjaWVfZGI=  # gestion_pharmacie_db in base64 