name: CI/CD Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  frontend:
    name: Frontend Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: Frontend_react/package-lock.json

      - name: Install dependencies
        working-directory: Frontend_react
        run: npm ci

      - name: Run tests
        working-directory: Frontend_react
        run: npm test

      - name: Run tests with coverage
        working-directory: Frontend_react
        run: npm run test:coverage

      - name: Build
        working-directory: Frontend_react
        run: npm run build

  backend:
    name: Backend Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'
          cache: 'maven'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('backend_spring/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven

      - name: Fix mvnw permissions
        working-directory: backend_spring
        run: chmod +x mvnw

      - name: Build & Test
        working-directory: backend_spring
        run: ./mvnw clean verify -Dspring.profiles.active=test
